FROM scratch
ADD oracle-7.tar.gz /

LABEL maintainer="Aleksander Baranowski <ab@euro-linux.com> (@AlexBaranowski)"
LABEL org.label-schema.schema-version="1.0" \
  org.label-schema.name="Oracle Linux 7" \
  org.label-schema.vendor="System - Oracle ®; Image - EuroLinux" \
  org.label-schema.url="https://euro-linux.com"\
  org.label-schema.vcs-url="https://github.com/EuroLinux/containers-rfc"\
  org.label-schema.license="GPLv2" \
  org.label-schema.build-date="20200901"

CMD ["/bin/bash"]
