FROM scratch
ADD oracle-7.tar.gz /

LABEL maintainer="EuroLinux Containers team <containers@euro-linux.com>" \
  name="oracle-linux-7" \
  vendor="System - Oracle ®; Image - EuroLinux" \
  url="https://euro-linux.com"\
  source="https://github.com/EuroLinux/containers-rfc"\
  licenses="GPLv2" \
  created="20231001" \
  architecture="x86_64" \
  summary="Oracle Linux 7 Base Container" \
  description="Provides Oracle Linux 7 Base Container" \
  version="7" \
  io.k8s.display-name="Oracle Linux 7 Base Container" \
  io.k8s.description="Provides Oracle Linux 7 Base Container" \
  io.openshift.tags="base oraclelinux"


CMD ["/bin/bash"]
