FROM scratch
ADD eurolinux-7.tar.gz /

LABEL maintainer="Aleksander Baranowski <ab@euro-linux.com> (@AlexBaranowski)"
LABEL org.label-schema.schema-version="1.0" \
  org.label-schema.name="EuroLinux 7" \
  org.label-schema.vendor="EuroLinux" \
  org.label-schema.url="https://euro-linux.com"\
  org.label-schema.vcs-url="https://github.com/EuroLinux/containers-rfc"\
  org.label-schema.license="GPLv2" \
  org.label-schema.build-date="20200101"

CMD ["/bin/bash"]
