FROM scratch
ADD eurolinux-7.tar.gz /

LABEL maintainer="EuroLinux Containers team <containers@euro-linux.com>" \
  name="eurolinux-7" \
  vendor="EuroLinux" \
  url="https://euro-linux.com"\
  source="https://github.com/EuroLinux/containers-rfc"\
  licenses="GPLv2" \
  created="20220701" \
  architecture="x86_64" \
  summary="EuroLinux 7 Base Container" \
  description="Provides EuroLinux 7 Base Container" \
  version="7" \
  io.k8s.display-name="EuroLinux 7 Base Container" \
  io.k8s.description="Provides EuroLinux 7 Base Container" \
  io.openshift.tags="base eurolinux"


CMD ["/bin/bash"]
