FROM scratch
ADD centos-stream-8.tar.gz /

LABEL maintainer="Aleksander Baranowski <ab@euro-linux.com> (@AlexBaranowski)"
LABEL org.label-schema.schema-version="1.0" \
  org.label-schema.name="CentOS Stream 8" \
  org.label-schema.vendor="System - CentOS Stream; Image - EuroLinux" \
  org.label-schema.url="https://euro-linux.com"\
  org.label-schema.vcs-url="https://github.com/EuroLinux/containers-rfc"\
  org.label-schema.license="GPLv2" \
  org.label-schema.build-date="20211228"

CMD ["/bin/bash"]
