FROM scratch
ADD centos-stream-8.tar.gz /

LABEL maintainer="EuroLinux Containers team <containers@euro-linux.com>" \
  name="centos-stream-8" \
  vendor="System - CentOS Stream; Image - EuroLinux" \
  url="https://euro-linux.com"\
  source="https://github.com/EuroLinux/containers-rfc"\
  licenses="GPLv2" \
  created="20240301" \
  architecture="x86_64" \
  summary="CentOS Stream 8 Base Container" \
  description="Provides CentOS Stream 8 Base Container" \
  version="8" \
  io.k8s.display-name="CentOS Stream 8 Base Container" \
  io.k8s.description="Provides CentOS Stream 8 Base Container" \
  io.openshift.tags="base centos centos-stream"


CMD ["/bin/bash"]
