FROM scratch
ADD rocky-9.tar.gz /

LABEL maintainer="EuroLinux Containers team <containers@euro-linux.com>" \
  name="rocky-9" \
  vendor="System - Rocky Linux; Image - EuroLinux" \
  url="https://euro-linux.com"\
  source="https://github.com/EuroLinux/containers-rfc"\
  licenses="GPLv2" \
  created="20230704" \
  architecture="x86_64" \
  summary="Rocky Linux 9 Base Container" \
  description="Provides Rocky Linux 9 Base Container" \
  version="9" \
  io.k8s.display-name="Rocky Linux 9 Base Container" \
  io.k8s.description="Provides RockyLinux 9 Base Container" \
  io.openshift.tags="base rockylinux"


CMD ["/bin/bash"]
