FROM scratch
ADD rocky-9.tar.gz /

LABEL maintainer="EuroLinux Containers team <containers@euro-linux.com>" \
  name="rocky-9" \
  vendor="System - RESF; Image - EuroLinux" \
  url="https://euro-linux.com"\
  source="https://github.com/EuroLinux/containers-rfc"\
  licenses="GPLv2" \
  created="20220801" \
  architecture="x86_64" \
  summary="RockyLinux 9 Base Container" \
  description="Provides RockyLinux 9 Base Container" \
  version="8" \
  io.k8s.display-name="RockyLinux 9 Base Container" \
  io.k8s.description="Provides RockyLinux 9 Base Container" \
  io.openshift.tags="base rockylinux"


CMD ["/bin/bash"]
