FROM scratch
ADD eurolinux-9.tar.gz /

LABEL maintainer="EuroLinux Containers team <containers@euro-linux.com>" \
  name="eurolinux-9" \
  vendor="System - EuroLinux; Image - EuroLinux" \
  url="https://euro-linux.com"\
  source="https://github.com/EuroLinux/containers-rfc"\
  licenses="GPLv2" \
  created="20231003" \
  architecture="x86_64" \
  summary="EuroLinux 9 Base Container" \
  description="Provides EuroLinux 9 Base Container" \
  version="9" \
  io.k8s.display-name="EuroLinux 9 Base Container" \
  io.k8s.description="Provides EuroLinux 9 Base Container" \
  io.openshift.tags="base eurolinux"


CMD ["/bin/bash"]
