FROM scratch
ADD centos-7.tar.gz /

LABEL maintainer="EuroLinux Containers team <containers@euro-linux.com>" \
  name="centos-7" \
  vendor="System - CentOS; Image - EuroLinux" \
  url="https://euro-linux.com"\
  source="https://github.com/EuroLinux/containers-rfc"\
  licenses="GPLv2" \
  created="20240501" \
  architecture="x86_64" \
  summary="CentOS 7 Base Container" \
  description="Provides CentOS 7 Base Container" \
  version="7" \
  io.k8s.display-name="CentOS 7 Base Container" \
  io.k8s.description="Provides CentOS 7 Base Container" \
  io.openshift.tags="base centos"


CMD ["/bin/bash"]
