FROM scratch
ADD eurolinux-8.tar.gz /

LABEL maintainer="EuroLinux Containers team <containers@euro-linux.com>" \
  name="eurolinux-8" \
  vendor="System - EuroLinux; Image - EuroLinux" \
  url="https://euro-linux.com"\
  source="https://github.com/EuroLinux/containers-rfc"\
  licenses="GPLv2" \
  created="20240901" \
  architecture="x86_64" \
  summary="EuroLinux 8 Base Container" \
  description="Provides EuroLinux 8 Base Container" \
  version="8" \
  io.k8s.display-name="EuroLinux 8 Base Container" \
  io.k8s.description="Provides EuroLinux 8 Base Container" \
  io.openshift.tags="base eurolinux"

ENV LOG4J_FORMAT_MSG_NO_LOOKUPS=true
CMD ["/bin/bash"]
