FROM scratch
ADD almalinux-9.tar.gz /

LABEL maintainer="EuroLinux Containers team <containers@euro-linux.com>" \
  name="almalinux-9" \
  vendor="System - AlmaLinux; Image - EuroLinux" \
  url="https://euro-linux.com"\
  source="https://github.com/EuroLinux/containers-rfc"\
  licenses="GPLv2" \
  created="20230704" \
  architecture="aarch64" \
  summary="AlmaLinux 9 Base Container" \
  description="Provides AlmaLinux 9 Base Container" \
  version="9" \
  io.k8s.display-name="AlmaLinux 9 Base Container" \
  io.k8s.description="Provides AlmaLinux 9 Base Container" \
  io.openshift.tags="base almalinux"


CMD ["/bin/bash"]
