FROM scratch
ADD centos-stream-9.tar.gz /

LABEL maintainer="EuroLinux Containers team <containers@euro-linux.com>" \
  name="centos-stream-9" \
  vendor="System - CentOS Stream; Image - EuroLinux" \
  url="https://euro-linux.com"\
  source="https://github.com/EuroLinux/containers-rfc"\
  licenses="GPLv2" \
  created="20240601" \
  architecture="aarch64" \
  summary="CentOS 9 Base Container" \
  description="Provides CentOS 9 Base Container" \
  version="9" \
  io.k8s.display-name="CentOS Stream 9 Base Container" \
  io.k8s.description="Provides CentOS 9 Base Container" \
  io.openshift.tags="base centos centos-stream"


CMD ["/bin/bash"]
