FROM scratch
ADD scientific-linux-7.tar.gz /

LABEL maintainer="EuroLinux Containers team <containers@euro-linux.com>" \
  name="scientific-linux-7" \
  vendor="System - Scientific Linux; Image - EuroLinux" \
  url="https://euro-linux.com"\
  source="https://github.com/EuroLinux/containers-rfc"\
  licenses="GPLv2" \
  created="20221001" \
  architecture="x86_64" \
  summary="Scientific Linux 7 Base Container" \
  description="Provides Scientific Linux 7 Base Container" \
  version="7" \
  io.k8s.display-name="Scientific Linux 7 Base Container" \
  io.k8s.description="Provides Scientific Linux 7 Base Container" \
  io.openshift.tags="base scientificlinux"


CMD ["/bin/bash"]
