FROM scratch
ADD eurolinux-9-micro.tar.gz /

LABEL maintainer="EuroLinux Containers team <containers@euro-linux.com>" \
  name="eurolinux-9-minimal" \
  vendor="System - EuroLinux; Image - EuroLinux" \
  url="https://euro-linux.com"\
  source="https://github.com/EuroLinux/containers-rfc"\
  licenses="GPLv2" \
  created="20240401" \
  architecture="aarch64" \
  summary="EuroLinux 9 Micro Base Container" \
  description="Provides EuroLinux 9 Micro Base Container" \
  version="9" \
  io.k8s.display-name="EuroLinux 9 Micro Base Container" \
  io.k8s.description="Provides EuroLinux 9 Micro Base Container" \
  io.openshift.tags="base eurolinux micro"


CMD ["/bin/sh"]
